hampir selesai

diff --git a/config b/config
--- a/config
+++ b/config
@@ -40,6 +40,21 @@ msg() {
   esac
 }
 
+cek_port() {
+  [[ $1 = "" ]] && echo -e "\033[1;31moff" && return 0
+  unset port
+  port_var=$(lsof -V -i -P -n | grep -v "ESTABLISHED" | grep -v "COMMAND")
+  i=0
+  while read port; do
+    var1=$(echo $port | awk '{print $1}') && var2=$(echo $port | awk '{print $9}' | awk -F ":" '{print $2}')
+    [[ "$(echo -e ${port[@]} | grep "$var1 $var2")" ]] || {
+      port[$i]="$var1 $var2\n"
+      let i++
+    }
+  done <<<"$port_var"
+  [[ $(echo "${port[@]}" | grep "$1") ]] && echo -e "\033[1;32mon" || echo -e "\033[1;31moff"
+}
+
 inst_comp() {
   msg -org "Menginstall $1"
   [[ $(dpkg --get-selections | grep -w "$1" | head -1) ]] || apt-get install $1 -y &>/dev/null
@@ -134,16 +149,24 @@ hapus_tool() {
   hapus_target ssr
   hapus_target addwg
   hapus_target vnstat
+  hapus_target stunnel
+  hapus_target openvpn
+
   hapus_ssh
   hapus_xray
   hapus_trojango
 
+  rm -rf $(whereis addhost) &>/dev/null
   ### Nginx port
   rm -rf /etc/nginx/sites-enabled/port80.conf /home/vps/ &>/dev/null
 }
 
 tanya() {
   read -p "$(msg -ne '$1 => ')" $2
+}
+
+cmd() {
+  $@ &>/dev/null || msg -warn "Error saat $1" && exit 1
 }
 
 ### Export Function
@@ -157,6 +180,8 @@ export -f hapus_ssh
 export -f hapus_xray
 export -f hapus_trojango
 export -f tanya
+export -f cmd
+export -f cek_port
 
 ### Export Variabel
 export HomeRepo="/root/ServerVPN"
